/**
 * Medical Prompt Templates Service
 *
 * Specialized prompt templates optimized for medical Q&A with Meditron.
 *
 * Features:
 * - Medical-specific prompt engineering
 * - Citation and provenance tracking
 * - Safety disclaimers
 * - Evidence-based response requirements
 * - Clinical entity extraction
 * - Treatment plan analysis
 *
 * Designed for use with Meditron (medical LLM) via Ollama.
 */

/**
 * Medical disclaimer configuration
 */
export interface MedicalDisclaimer {
  enabled: boolean;
  shortForm: string;
  longForm: string;
}

/**
 * Prompt template options
 */
export interface PromptOptions {
  includeDisclaimer?: boolean;
  requireCitations?: boolean;
  requireConfidenceLevel?: boolean;
  maxTokens?: number;
  temperature?: number;
}

/**
 * Clinical entity types to extract
 */
export enum ClinicalEntityType {
  MEDICATION = 'medication',
  DIAGNOSIS = 'diagnosis',
  PROCEDURE = 'procedure',
  LAB_RESULT = 'lab_result',
  VITAL_SIGN = 'vital_sign',
  ALLERGY = 'allergy',
  SYMPTOM = 'symptom',
}

/**
 * Treatment plan component
 */
export interface TreatmentPlanComponent {
  medications?: boolean;
  procedures?: boolean;
  followUp?: boolean;
  patientEducation?: boolean;
  labOrders?: boolean;
}

/**
 * Medical Prompt Templates Service
 */
class MedicalPromptTemplatesService {
  /**
   * Default medical disclaimer
   */
  private readonly DEFAULT_DISCLAIMER: MedicalDisclaimer = {
    enabled: true,
    shortForm:
      'This information is for educational purposes only and does not constitute medical advice.',
    longForm:
      '⚠️ MEDICAL DISCLAIMER: This information is generated by an AI system and is for ' +
      'informational purposes only. It does NOT constitute medical advice, diagnosis, or treatment. ' +
      'Always consult with qualified healthcare professionals for medical decisions.',
  };

  /**
   * Medical question answering prompt with citations
   *
   * Optimized for Meditron to answer clinical questions based on retrieved context.
   * Requires citations to source artifacts and includes confidence levels.
   *
   * @param question - Medical question to answer
   * @param context - Array of context chunks with artifact IDs
   * @param options - Prompt options
   * @returns Formatted prompt for Meditron
   *
   * @example
   * const prompt = medicalQA(
   *   "What medications is the patient taking for hypertension?",
   *   ["Artifact ID: art_001\nContent: Patient prescribed lisinopril 10mg daily..."]
   * );
   */
  medicalQA(question: string, context: string[], options: PromptOptions = {}): string {
    const {
      includeDisclaimer = true,
      requireCitations = true,
      requireConfidenceLevel = true,
    } = options;

    const systemPrompt = this.buildSystemPrompt('medical_qa');
    const contextBlock = this.buildContextBlock(context);
    const citationInstructions = requireCitations
      ? '\n- Cite the source artifact ID for each fact in square brackets [artifact_id]'
      : '';
    const confidenceInstructions = requireConfidenceLevel
      ? '\n- Indicate confidence level: High (strong evidence), Medium (some evidence), or Low (limited evidence)'
      : '';
    const disclaimerText = includeDisclaimer ? `\n\n${this.DEFAULT_DISCLAIMER.longForm}` : '';

    return `${systemPrompt}

INSTRUCTIONS:
Answer the medical question based ONLY on the provided clinical information.
Do NOT use external medical knowledge or add information not present in the context.
If the information needed to answer is not in the provided context, respond with:
"The requested information is not available in the patient's records provided."

Requirements:${citationInstructions}${confidenceInstructions}
- Use precise medical terminology
- Be concise but complete
- Prioritize patient safety in all recommendations

CONTEXT:
${contextBlock}

QUESTION:
${question}

ANSWER:${disclaimerText}`;
  }

  /**
   * Clinical entity extraction prompt
   *
   * Extracts structured clinical entities from medical text.
   * Returns JSON with standardized medical terminology.
   *
   * @param text - Clinical text to extract from
   * @param entityTypes - Types of entities to extract (default: all)
   * @param options - Prompt options
   * @returns Formatted prompt for entity extraction
   *
   * @example
   * const prompt = extractClinicalEntities(
   *   "Patient presents with hypertension. Prescribed lisinopril 10mg daily.",
   *   [ClinicalEntityType.DIAGNOSIS, ClinicalEntityType.MEDICATION]
   * );
   */
  extractClinicalEntities(
    text: string,
    entityTypes: ClinicalEntityType[] = Object.values(ClinicalEntityType),
    _options: PromptOptions = {}
  ): string {
    const systemPrompt = this.buildSystemPrompt('entity_extraction');
    const entityTypesList = entityTypes.join(', ');

    const jsonSchema = this.buildEntityExtractionSchema(entityTypes);

    return `${systemPrompt}

TASK:
Extract clinical entities from the provided medical text.

ENTITY TYPES TO EXTRACT:
${entityTypesList}

OUTPUT FORMAT:
Return a valid JSON object with the following structure:
${jsonSchema}

REQUIREMENTS:
- Use standardized medical terminology (e.g., "hypertension" not "high blood pressure")
- Include dosage, frequency, and route for medications
- Include values and units for lab results and vital signs
- Use ICD-10 codes when applicable for diagnoses
- Extract dates/times when mentioned
- If an entity type is not found, use an empty array

CLINICAL TEXT:
${text}

EXTRACTED ENTITIES (JSON):`;
  }

  /**
   * Medical record summarization prompt
   *
   * Summarizes medical records in standard clinical format.
   * Uses SOAP (Subjective, Objective, Assessment, Plan) structure.
   *
   * @param record - Full medical record or note
   * @param format - Summary format (default: 'soap')
   * @param options - Prompt options
   * @returns Formatted prompt for summarization
   *
   * @example
   * const prompt = summarizeMedicalRecord(
   *   "Patient presents with...",
   *   'soap'
   * );
   */
  summarizeMedicalRecord(
    record: string,
    format: 'soap' | 'brief' | 'detailed' = 'soap',
    _options: PromptOptions = {}
  ): string {
    const systemPrompt = this.buildSystemPrompt('summarization');
    const formatInstructions = this.getSummaryFormatInstructions(format);

    return `${systemPrompt}

TASK:
Summarize the following medical record in ${format.toUpperCase()} format.

${formatInstructions}

REQUIREMENTS:
- Use standard medical abbreviations (e.g., HTN, DM, CAD, COPD)
- Keep summary concise but clinically relevant
- Highlight critical findings and patient safety concerns
- Include dates for key events
- Maintain chronological order
- Do NOT add information not present in the record

MEDICAL RECORD:
${record}

SUMMARY:`;
  }

  /**
   * Treatment plan analysis prompt
   *
   * Analyzes treatment plans for completeness, safety, and evidence-based recommendations.
   *
   * @param plan - Treatment plan text
   * @param components - Which components to analyze
   * @param options - Prompt options
   * @returns Formatted prompt for treatment plan analysis
   *
   * @example
   * const prompt = analyzeTreatmentPlan(
   *   "Start metformin 500mg BID...",
   *   { medications: true, followUp: true }
   * );
   */
  analyzeTreatmentPlan(
    plan: string,
    components: TreatmentPlanComponent = {},
    _options: PromptOptions = {}
  ): string {
    const {
      medications = true,
      procedures = true,
      followUp = true,
      patientEducation = true,
      labOrders = true,
    } = components;

    const systemPrompt = this.buildSystemPrompt('treatment_analysis');

    const analysisComponents: string[] = [];
    if (medications) analysisComponents.push('- Medications: doses, frequencies, interactions');
    if (procedures) analysisComponents.push('- Procedures: indications, risks, alternatives');
    if (followUp) analysisComponents.push('- Follow-up: timeline, monitoring parameters');
    if (patientEducation)
      analysisComponents.push('- Patient education: lifestyle, warning signs');
    if (labOrders) analysisComponents.push('- Lab orders: baseline tests, monitoring labs');

    return `${systemPrompt}

TASK:
Analyze the following treatment plan for completeness and safety.

ANALYSIS COMPONENTS:
${analysisComponents.join('\n')}

REQUIREMENTS:
- Identify any potential safety concerns (drug interactions, contraindications)
- Note missing elements that should be included
- Assess alignment with evidence-based guidelines
- Highlight urgent/critical items
- Suggest improvements if plan is incomplete

OUTPUT FORMAT:
1. Safety Assessment: (any concerns or "No safety concerns identified")
2. Completeness: (missing elements or "Plan is complete")
3. Evidence-Based Recommendations: (suggestions aligned with clinical guidelines)
4. Overall Assessment: (brief summary)

TREATMENT PLAN:
${plan}

ANALYSIS:`;
  }

  /**
   * Differential diagnosis prompt
   *
   * Generates differential diagnosis based on symptoms and findings.
   * Prioritizes by likelihood and includes supporting evidence.
   *
   * @param presentation - Patient presentation (symptoms, signs, findings)
   * @param maxDiagnoses - Maximum number of differential diagnoses (default: 5)
   * @param options - Prompt options
   * @returns Formatted prompt for differential diagnosis
   *
   * @example
   * const prompt = differentialDiagnosis(
   *   "65yo M with chest pain, diaphoresis, SOB...",
   *   5
   * );
   */
  differentialDiagnosis(
    presentation: string,
    maxDiagnoses: number = 5,
    _options: PromptOptions = {}
  ): string {
    const systemPrompt = this.buildSystemPrompt('differential_diagnosis');

    return `${systemPrompt}

TASK:
Based on the patient presentation, provide a differential diagnosis list.

INSTRUCTIONS:
- List up to ${maxDiagnoses} possible diagnoses in order of likelihood (most likely first)
- For each diagnosis, provide:
  * Diagnosis name
  * Supporting evidence from the presentation
  * Key distinguishing features
  * Next steps for confirmation/exclusion

REQUIREMENTS:
- Consider life-threatening conditions first (e.g., MI, PE, sepsis)
- Use clinical reasoning and pattern recognition
- Note if critical information is missing
- Suggest additional tests/workup needed

OUTPUT FORMAT:
1. [Diagnosis Name]
   - Likelihood: High/Medium/Low
   - Supporting Evidence: [specific findings from presentation]
   - Distinguishing Features: [what makes this diagnosis likely]
   - Next Steps: [tests/imaging to confirm or rule out]

PATIENT PRESENTATION:
${presentation}

DIFFERENTIAL DIAGNOSIS:`;
  }

  /**
   * Medication reconciliation prompt
   *
   * Reconciles medication lists to identify discrepancies, duplications, and interactions.
   *
   * @param currentMeds - Current medication list
   * @param reportedMeds - Patient-reported medications
   * @param options - Prompt options
   * @returns Formatted prompt for medication reconciliation
   *
   * @example
   * const prompt = medicationReconciliation(
   *   "lisinopril 10mg daily, metformin 500mg BID",
   *   "blood pressure pill, diabetes medicine"
   * );
   */
  medicationReconciliation(
    currentMeds: string,
    reportedMeds: string,
    _options: PromptOptions = {}
  ): string {
    const systemPrompt = this.buildSystemPrompt('medication_reconciliation');

    return `${systemPrompt}

TASK:
Reconcile medication lists to identify discrepancies and ensure medication safety.

INSTRUCTIONS:
Compare the current medication list (from medical records) with the patient-reported medications.
Identify:
- Matching medications
- Discrepancies (different doses, frequencies, or missing medications)
- Potential duplications (same drug class)
- Potential drug-drug interactions
- Medications that need clarification

CURRENT MEDICATION LIST (Medical Record):
${currentMeds}

PATIENT-REPORTED MEDICATIONS:
${reportedMeds}

OUTPUT FORMAT:
1. MATCHED MEDICATIONS:
   [List medications that match between both lists]

2. DISCREPANCIES:
   [List differences in dose, frequency, or missing medications]

3. POTENTIAL INTERACTIONS:
   [Note any concerning drug interactions]

4. RECOMMENDATIONS:
   [Actions needed: clarify with patient, update record, etc.]

MEDICATION RECONCILIATION:`;
  }

  /**
   * Lab result interpretation prompt
   *
   * Interprets lab results in clinical context, noting abnormalities and clinical significance.
   *
   * @param labResults - Lab results with values and reference ranges
   * @param clinicalContext - Patient's clinical context (diagnoses, medications)
   * @param options - Prompt options
   * @returns Formatted prompt for lab interpretation
   *
   * @example
   * const prompt = labResultInterpretation(
   *   "HbA1c: 8.2% (ref: 4.0-5.6%)",
   *   "Patient with Type 2 DM on metformin"
   * );
   */
  labResultInterpretation(
    labResults: string,
    clinicalContext: string = '',
    _options: PromptOptions = {}
  ): string {
    const systemPrompt = this.buildSystemPrompt('lab_interpretation');

    const contextSection = clinicalContext
      ? `CLINICAL CONTEXT:\n${clinicalContext}\n\n`
      : '';

    return `${systemPrompt}

TASK:
Interpret the following lab results and explain their clinical significance.

${contextSection}LAB RESULTS:
${labResults}

INSTRUCTIONS:
For each abnormal result:
- Identify the abnormality (high, low, critical)
- Explain clinical significance
- Consider potential causes in the clinical context
- Suggest follow-up actions if needed

OUTPUT FORMAT:
1. NORMAL RESULTS:
   [List results within reference range]

2. ABNORMAL RESULTS:
   [For each abnormal result:]
   - Test: [name]
   - Value: [value with reference range]
   - Interpretation: [clinical significance]
   - Possible Causes: [list relevant to clinical context]
   - Recommended Actions: [monitoring, repeat testing, further workup]

3. CRITICAL VALUES:
   [Flag any life-threatening results requiring immediate action]

INTERPRETATION:`;
  }

  /**
   * Build system prompt based on task type
   *
   * @param taskType - Type of medical task
   * @returns System prompt for the task
   */
  private buildSystemPrompt(taskType: string): string {
    const basePrompt = 'You are a medical information assistant with expertise in clinical reasoning.';

    const taskSpecificPrompts: Record<string, string> = {
      medical_qa:
        basePrompt +
        '\n\nYour role is to answer medical questions accurately based on provided clinical information. ' +
        'You must cite sources and indicate confidence levels. Never add information not present in the context.',

      entity_extraction:
        basePrompt +
        '\n\nYour role is to extract structured clinical entities from medical text. ' +
        'Use standardized medical terminology and return valid JSON format.',

      summarization:
        basePrompt +
        '\n\nYour role is to summarize medical records in standard clinical format. ' +
        'Be concise, use medical abbreviations appropriately, and highlight critical information.',

      treatment_analysis:
        basePrompt +
        '\n\nYour role is to analyze treatment plans for safety, completeness, and alignment with evidence-based guidelines. ' +
        'Identify potential issues and provide constructive recommendations.',

      differential_diagnosis:
        basePrompt +
        '\n\nYour role is to generate differential diagnoses based on patient presentations. ' +
        'Consider life-threatening conditions first and use clinical reasoning.',

      medication_reconciliation:
        basePrompt +
        '\n\nYour role is to reconcile medication lists and identify discrepancies, duplications, and interactions. ' +
        'Ensure medication safety.',

      lab_interpretation:
        basePrompt +
        '\n\nYour role is to interpret laboratory results and explain their clinical significance. ' +
        'Flag critical values and provide actionable recommendations.',
    };

    return taskSpecificPrompts[taskType] || basePrompt;
  }

  /**
   * Build context block from context chunks
   *
   * @param context - Array of context strings (with artifact IDs)
   * @returns Formatted context block
   */
  private buildContextBlock(context: string[]): string {
    if (context.length === 0) {
      return '[No clinical information provided]';
    }

    return context
      .map((chunk, index) => {
        return `--- Context Chunk ${index + 1} ---\n${chunk}`;
      })
      .join('\n\n');
  }

  /**
   * Build JSON schema for entity extraction
   *
   * @param entityTypes - Types of entities to extract
   * @returns JSON schema as string
   */
  private buildEntityExtractionSchema(entityTypes: ClinicalEntityType[]): string {
    const schemas: Record<ClinicalEntityType, string> = {
      [ClinicalEntityType.MEDICATION]: `  "medications": [
    {
      "name": "string",
      "dose": "string",
      "frequency": "string",
      "route": "string",
      "start_date": "string (optional)"
    }
  ]`,
      [ClinicalEntityType.DIAGNOSIS]: `  "diagnoses": [
    {
      "name": "string",
      "icd10_code": "string (optional)",
      "status": "active|resolved|history",
      "date": "string (optional)"
    }
  ]`,
      [ClinicalEntityType.PROCEDURE]: `  "procedures": [
    {
      "name": "string",
      "cpt_code": "string (optional)",
      "date": "string (optional)",
      "location": "string (optional)"
    }
  ]`,
      [ClinicalEntityType.LAB_RESULT]: `  "lab_results": [
    {
      "test_name": "string",
      "value": "string",
      "unit": "string",
      "reference_range": "string (optional)",
      "date": "string (optional)"
    }
  ]`,
      [ClinicalEntityType.VITAL_SIGN]: `  "vital_signs": [
    {
      "type": "BP|HR|Temp|RR|SpO2|Weight|Height",
      "value": "string",
      "unit": "string",
      "date": "string (optional)"
    }
  ]`,
      [ClinicalEntityType.ALLERGY]: `  "allergies": [
    {
      "allergen": "string",
      "reaction": "string",
      "severity": "mild|moderate|severe",
      "date": "string (optional)"
    }
  ]`,
      [ClinicalEntityType.SYMPTOM]: `  "symptoms": [
    {
      "symptom": "string",
      "severity": "mild|moderate|severe (optional)",
      "onset": "string (optional)",
      "duration": "string (optional)"
    }
  ]`,
    };

    const selectedSchemas = entityTypes.map((type) => schemas[type]).filter(Boolean);

    return `{
${selectedSchemas.join(',\n')}
}`;
  }

  /**
   * Get summary format instructions
   *
   * @param format - Summary format type
   * @returns Format-specific instructions
   */
  private getSummaryFormatInstructions(format: 'soap' | 'brief' | 'detailed'): string {
    const instructions: Record<string, string> = {
      soap: `SOAP FORMAT:
- S (Subjective): Patient's symptoms, complaints, and history
- O (Objective): Physical exam findings, vital signs, lab results
- A (Assessment): Diagnoses and clinical reasoning
- P (Plan): Treatment plan, medications, follow-up`,

      brief: `BRIEF FORMAT:
- Chief complaint
- Key diagnoses
- Current medications
- Active problems
Limit to 100 words or less.`,

      detailed: `DETAILED FORMAT:
- Chief Complaint
- History of Present Illness
- Past Medical History
- Medications
- Allergies
- Physical Examination
- Laboratory Results
- Assessment
- Plan
Provide comprehensive summary with all relevant clinical details.`,
    };

    return instructions[format];
  }

  /**
   * Get medical disclaimer
   *
   * @param format - 'short' or 'long'
   * @returns Disclaimer text
   */
  getMedicalDisclaimer(format: 'short' | 'long' = 'long'): string {
    return format === 'short'
      ? this.DEFAULT_DISCLAIMER.shortForm
      : this.DEFAULT_DISCLAIMER.longForm;
  }

  /**
   * Append disclaimer to response
   *
   * @param response - Generated response
   * @param format - Disclaimer format
   * @returns Response with disclaimer appended
   */
  appendDisclaimer(response: string, format: 'short' | 'long' = 'long'): string {
    const disclaimer = this.getMedicalDisclaimer(format);
    return `${response}\n\n${disclaimer}`;
  }
}

// Export singleton instance
const medicalPromptTemplates = new MedicalPromptTemplatesService();
export default medicalPromptTemplates;
